version: '3'
services:
  nodejs-app-web:
    build: .
#    image: 562720243559.dkr.ecr.ap-south-1.amazonaws.com/docker-apps:1.3
    ports:
      - "3000:3000"
#    environment:
#        MONGO_URL: mongodb://admin:password@nodejs-app-mongodb:27017
  nodejs-app-mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
  nodejs-app-mongodb-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
        ME_CONFIG_MONGODB_SERVER: nodejs-app-mongodb
    depends_on:
      - nodejs-app-mongodb