version: '3'
services:
  nodejs-app-web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - nodejs-app-mongodb
    links:
      - nodejs-app-mongodb
  nodejs-app-mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
  nodejs-app-mongodb-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
        ME_CONFIG_MONGODB_SERVER: nodejs-app-mongodb
    depends_on:
      - nodejs-app-mongodb